### ISSUE TITLE
Work on Pi 4 and would import data

### ISSUE THREAD

**Issue by rmc0** [zusam/zusam_ynh#2]
Thank for porting in yunohost, 

Install ok on Pi 4  YunoHost 4.0.8.3 (stable)

I would import data ( users account and pictures of another machine)

Do you have idea for do this clean or juste copy some folders (?)

**Comment by nrobinaubertin** [comment]
Hi, thanks for your feedback.

All the data of zusam is situated in a `data/` directory that is next to the `public/` directory serving the html. Just copying this directory should do the trick (it has a configuration file, a database file `data.db`, a `files/` directory for all uploaded files and a `cache/` directory that stores some cache data).

The default installation directory for zusam on yunohost is `/var/www/zusam`, you should replace the `data/` directory there with the one you already have. Be sure to `chown www-data: -R /var/www/zusam/data` after that (and `chmod 750 -R /var/www/zusam/data` to be sure that it's readable).

**Comment by rmc0** [comment]
Hi, 

that work fine ! 

thank
